Biseccion
ZabreLight/tp-superior pull request #3
Opened 2018-07-09 23:22 UTC by fedejinich

2018-07-09 23:28 UTC, ZabreLight requested changes

2018-07-09 23:28 UTC, ZabreLight commented on src/screens/home/index.js
> +    this.setState({ columns: columns, data: data });
`this.setState({ columns, data });`

2018-07-09 23:28 UTC, ZabreLight commented on src/screens/home/index.js
> +    this.setState({ columns: columns, data: data });
same

2018-07-09 23:28 UTC, ZabreLight commented on src/screens/home/index.js
> +    this.setState({ columns: columns, data: data });
same

2018-07-09 23:28 UTC, ZabreLight commented on src/screens/home/layout.js
> +//import { columns } from './constants';
Borra el comentario

2018-07-09 23:28 UTC, ZabreLight commented on src/screens/home/utils.js
> +    return {columns: columns, data:resultados};
`{columns, data: resultados};`

2018-07-09 23:28 UTC, ZabreLight commented on src/screens/home/utils.js
> +    return {columns: columns, data:resultados};
Same

2018-07-09 23:28 UTC, ZabreLight commented on src/screens/home/utils.js
> +    // resultados.push({xn, iteracion, xnAnterior, error});
Borra el comentario

2018-07-10 00:48 UTC, fedejinich commented
ya esta listo todo

2018-07-10 00:48 UTC, closed without merging